contact_links:
  - name: Zgłoś lukę w zabezpieczeniach
    url: https://github.com/space-wizards/space-station-14/blob/master/SECURITY.md
    about: "Prosimy o zgłaszanie luk w zabezpieczeniach prywatnie, abyśmy mogli je naprawić przed ich publicznym ujawnieniem" - Wizards
